pw_docgen: sphinxcontrib-mermaid workaround:
Version >=4.0.0 of Sphinx removes some APIs, one of which is used by
sphinxcontrib-mermaid. Error:

Running Sphinx v4.0.0
Extension error:
Could not import extension sphinxcontrib.mermaid (exception: cannot import name
'ENOENT' from 'sphinx.util.osutil'

Failed roll:
https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/44223

This workaround can be removed after
https://github.com/mgaitan/sphinxcontrib-mermaid/pull/71 is merged.

No-Docs-Update-Reason: Sphinx 4.0 workaround.
Change-Id: I63e192428dda4efa228dea892ef857c782ec5674
Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/44320
Commit-Queue: Anthony DiGirolamo <tonymd@google.com>
Pigweed-Auto-Submit: Anthony DiGirolamo <tonymd@google.com>
Reviewed-by: Rob Mohr <mohrr@google.com>