pw_cpu_exception: Add CPU exception module
This change introduces pw_cpu_exception, a facade that provides a
high-level interface for handling CPU exceptions.

Change-Id: I1f98ac82dd54040448b2e2ac32a392c49cb6dfba