pw_console: Missing default_factory for dataclasses
Fixes the Python 3.11 error:
ValueError: mutable default <class 'collections.deque'> for field
history is not allowed: use default_factory.

Change-Id: Ibbb7ff150d704851c14b3e0b2247d264931e898b
Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/135481
Pigweed-Auto-Submit: Anthony DiGirolamo <tonymd@google.com>
Commit-Queue: Auto-Submit <auto-submit@pigweed.google.com.iam.gserviceaccount.com>
Reviewed-by: Rob Mohr <mohrr@google.com>