pw_cpu_exception: On-device exception analyzer
Extends pw_cpu_exception_armv7m's LogCpuState() to analyze the provided
CPU context to provide insight into the cause of the exception.

Change-Id: I8f706d0e88fefb5a9205435d819abfeee530407c
Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/29380
Commit-Queue: Armando Montanez <amontanez@google.com>
Reviewed-by: Ewout van Bekkum <ewout@google.com>