pw_cli: Fix logging msec format
Python 3.8 and lower does not check if default_msec_format is set.
Fixes these Logging errors:

```
TypeError: not all arguments converted during string formatting
```

Change-Id: I9b1a54407556e7e54fd77583abbb52ca5b07a309
Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/130472
Commit-Queue: Auto-Submit <auto-submit@pigweed.google.com.iam.gserviceaccount.com>
Pigweed-Auto-Submit: Anthony DiGirolamo <tonymd@google.com>
Reviewed-by: Wyatt Hepler <hepler@google.com>